version: '3.7'
services:
  springboot-graphql-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-graphql-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=def_user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=moviesdb
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgres/sql/postgresql.conf